//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefactoringDog.Application.Literals {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessagesDogs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesDogs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RefactoringDog.Application.Literals.MessagesDogs", typeof(MessagesDogs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adopting.
        /// </summary>
        public static string DogAdopting {
            get {
                return ResourceManager.GetString("DogAdopting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I will call Police.
        /// </summary>
        public static string DogCallPolice {
            get {
                return ResourceManager.GetString("DogCallPolice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WTF this not suppouse to be alive???. I will call the Zoo.
        /// </summary>
        public static string DogCallZoo {
            get {
                return ResourceManager.GetString("DogCallZoo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dog its to danguerous to be Deposit. Dont come back..
        /// </summary>
        public static string DogDangerous {
            get {
                return ResourceManager.GetString("DogDangerous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depositing.
        /// </summary>
        public static string DogDepositing {
            get {
                return ResourceManager.GetString("DogDepositing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dog its {0}.
        /// </summary>
        public static string DogDescription {
            get {
                return ResourceManager.GetString("DogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are full :(. Why dont you Adopt one.
        /// </summary>
        public static string DogFull {
            get {
                return ResourceManager.GetString("DogFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dog killer.
        /// </summary>
        public static string DogKiller {
            get {
                return ResourceManager.GetString("DogKiller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We dont have the dog you want.
        /// </summary>
        public static string DogNotHave {
            get {
                return ResourceManager.GetString("DogNotHave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dog its to older to be Deposit. Dont come back..
        /// </summary>
        public static string DogOlder {
            get {
                return ResourceManager.GetString("DogOlder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must pay: {0} on the cash register.
        /// </summary>
        public static string DogPayCashRegister {
            get {
                return ResourceManager.GetString("DogPayCashRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People eater.
        /// </summary>
        public static string DogPeopeEater {
            get {
                return ResourceManager.GetString("DogPeopeEater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ------------------------------------------------------------------------------------.
        /// </summary>
        public static string DogSeparator {
            get {
                return ResourceManager.GetString("DogSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dog its to small to be Deposit. Come back when the dog were older than 1 year..
        /// </summary>
        public static string DogSmall {
            get {
                return ResourceManager.GetString("DogSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0} this is the ticket conforming you are {1} a dog to us..
        /// </summary>
        public static string DogTicket {
            get {
                return ResourceManager.GetString("DogTicket", resourceCulture);
            }
        }
    }
}
